### ISSUE TITLE
创建绘画失败,可能相关图画描述及种子图已存在,请查看历史生成图

### ISSUE THREAD

**Issue by cdpurchase1** [newlxj/sdweb-multi-user-website#4]
点击生成后一直提示“创建绘画失败,可能相关图画描述及种子图已存在,请查看历史生成图”，这个是什么问题呢？

**Comment by cdpurchase1** [comment]
报错信息
[2023-06-21 17:36:55,815] ERROR in app: Exception on /api/create [POST]
Traceback (most recent call last):
  File "D:\SD\SDF\sdweb-multi-user-website\sdweb-server\ai8-env\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\SD\SDF\sdweb-multi-user-website\sdweb-server\ai8-env\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\SD\SDF\sdweb-multi-user-website\sdweb-server\ai8-env\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\SD\SDF\sdweb-multi-user-website\sdweb-server\ai8-env\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\SD\SDF\sdweb-multi-user-website\sdweb-server\api\stablediffusion.py", line 97, in create
    hires_upscale = info["extra_generation_params"]["Hires upscale"]
KeyError: 'Hires upscale'
127.0.0.1 - - [2023-06-21 17:36:55] "POST /api/create HTTP/1.1" 500 401 2.881064
/api/process
ltsmSxm8rBTzMZslgGm8RdheQzOZl9SSGrDX17IcGeJcyPM139QeKfgsabneBXGEkTaszvItfwxx7JWRV/RAKg==
127.0.0.1 - - [2023-06-21 17:36:55] "POST /api/process HTTP/1.1" 200 461 0.051609

在远程stable diffusion有看到api请求，但进度条跑完之后，就提示“创建绘画失败,可能相关图画描述及种子图已存在,请查看历史生成图”

**Comment by onlinedear** [comment]
感觉作者好久不关注这个项目了 很可惜 多么好的一个项目

**Comment by newlxj** [comment]
不好意思，最近有点忙，这个应该是最开始防止用户一直生成同一个图片出现攻击做了一个限制，这个可以在保存图片时给图片增加一个随机数解决，每次生成时给数据库插入主键时，如果主键冲突就会提示这个

**Comment by newlxj** [comment]
> 感觉作者好久不关注这个项目了 很可惜 多么好的一个项目

抱歉，这几天没上来看，也可以QQ群找到我留言

**Comment by newlxj** [comment]
> 

你这个我本地验证了一下，只有两种情况
1.种子重复了，你可以自己去补充随机数避免想通种子重复
2.sd报错了导致前端显示这个错误。
